'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var REMOVE_FIELD = exports.REMOVE_FIELD = 'REMOVE_FIELD';
var EDIT_FIELD = exports.EDIT_FIELD = 'EDIT_FIELD';
var VALIDATE_FIELD = exports.VALIDATE_FIELD = 'VALIDATE_FIELD';
var ADD_MANY_CHILD = exports.ADD_MANY_CHILD = 'ADD_MANY_CHILD';
var REMOVE_MANY_CHILD = exports.REMOVE_MANY_CHILD = 'REMOVE_MANY_CHILD';
var EDIT_MANY_CHILDREN = exports.EDIT_MANY_CHILDREN = 'EDIT_MANY_CHILDREN';
var REORDER_MANY_CHILDREN = exports.REORDER_MANY_CHILDREN = 'REORDER_MANY_CHILDREN';
var VALIDATE_MANY = exports.VALIDATE_MANY = 'VALIDATE_MANY';