'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var DELETE_FIELD = exports.DELETE_FIELD = 'DELETE_FIELD';
var EDIT_FIELD = exports.EDIT_FIELD = 'EDIT_FIELD';
var VALIDATE_FIELD = exports.VALIDATE_FIELD = 'VALIDATE_FIELD';
var ADD_MANY_CONTENT = exports.ADD_MANY_CONTENT = 'ADD_MANY_CONTENT';
var DELETE_MANY_CONTENT = exports.DELETE_MANY_CONTENT = 'DELETE_MANY_CONTENT';
var EDIT_MANY_CONTENTS = exports.EDIT_MANY_CONTENTS = 'EDIT_MANY_CONTENTS';
var REORDER_MANY_CONTENTS = exports.REORDER_MANY_CONTENTS = 'REORDER_MANY_CONTENTS';
var VALIDATE_MANY = exports.VALIDATE_MANY = 'VALIDATE_MANY';